package ats.metro;

import java.util.List;

/**
 * This is the representation of notes in a bar. Bars are usually generated by
 * the tracks. See
 * {@link MetroTrack#progressCursor(int, List) } for further
 * information.
 * 
 * @author ats
 */
public interface MetroAbstractEvent {
	boolean between(int from, int to);
	void process(Metro metro, int from, int to, int nframes, List<MetroAbstractMidiEvent> eventList);
}