(begin
  (import (srfi 1))
  (import (srfi 26))
  (import (kawa pprint))
  (import (lamu evaluators))
  (import (lamu procs))
  (import (lamu scheme))
  (import (lamu notes))
  (import (lamu music))
  (import (lamu song))
  (import (lamu pulsar))
  (import (lamu evaluators)))
